# Generated by Django 5.1.3 on 2024-12-27 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dept',
            old_name='deptid',
            new_name='depno',
        ),
        migrations.RenameField(
            model_name='emp',
            old_name='deptid',
            new_name='deptno',
        ),
        migrations.RenameField(
            model_name='emp',
            old_name='empid',
            new_name='empno',
        ),
    ]
