# Generated by Django 5.1.3 on 2024-12-27 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0002_rename_deptid_dept_depno_rename_deptid_emp_deptno_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dept',
            old_name='deptloc',
            new_name='dept_loc',
        ),
        migrations.RenameField(
            model_name='dept',
            old_name='deptname',
            new_name='dept_name',
        ),
        migrations.RenameField(
            model_name='dept',
            old_name='depno',
            new_name='dept_no',
        ),
        migrations.RenameField(
            model_name='emp',
            old_name='ename',
            new_name='empname',
        ),
    ]
